Repository AndcultureCode/AndcultureCode.Cli, pull requests merged in 2019-10, with the labels that each got.

#21 Add newlines as well as comments for cli-install to fix issue #20
  cli-install.js
Labels: bug, hacktoberfest

#23 Feature/acc 15 ef core add remove migrations
  _modules/commands.js
  _modules/dotnet-path.js
  _modules/migration.js
  cli-migration.js
Labels: enhancement, hacktoberfest

#32 Feature issue #29 deploy webpack aws s3
  COMMANDS.md
  README.md
  _modules/commands.js
  _modules/dotnet-path.js
  _modules/dotnet-publish.js
  _modules/echo.js
  _modules/frontend-path.js
  _modules/webpack-publish.js
  cli-copy.js
  cli-deploy-aws-beanstalk.js
  cli-deploy-aws-s3.js
  cli-dotnet.js
  cli-webpack.js
  cli.js
Labels: enhancement

#36 Issue #35 - Increase default awsebcli timeout from 10 to 20 and accept override
  cli-deploy-aws-beanstalk.js
Labels: bug

#34 Issue #33 - Force installation of compatible AWS CLI and AWS EB CLIs
  cli-deploy-aws-beanstalk.js
  cli-deploy-aws-s3.js
Labels: bug
